name: Test Environments


on:
  push:
    branches:
      - master
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  test-pr:
    name: Testing Pr
    runs-on: ubuntu-latest
    steps:
      - run: echo "hello pr"
  
  test-dev:
    if: ${{ github.event_name == 'push' }}
    name: Testing Dev
    runs-on: ubuntu-latest
    environment:
      name: dev
    steps:
      - run: echo "hello ${{ secrets.mysecret }}"

  test-prod:
    if: ${{ github.event_name == 'push' }}
    name: Testing Prod
    runs-on: ubuntu-latest
    environment:
      name: prod
    steps:
      - run: echo "hello ${{ secrets.mysecret }}"