name: Test Environments


on:
  push:
    branches:
      - master
  pull_request:
    types: [opened, synchronize, reopened]
  workflow_dispatch: {}

jobs:
  test-pr:
    name: Testing Pr
    runs-on: ubuntu-latest
    steps:
      - run: echo "hello pr"
  
  test-dev:
    if: ${{ github.event_name == 'push' }}
    name: Testing Dev
    runs-on: ubuntu-latest
    environment:
      name: dev
    steps:
      - run: echo "hello ${{ secrets.mysecret }}"

  test-prod:
    if: ${{ github.event_name == 'push' }}
    name: Testing Prod
    runs-on: ubuntu-latest
    steps:
      - run: echo "hello ${{ secrets.mysecret }}"
      
  always-after-prod:
    needs: test-prod
    runs-on: ubuntu-latest
    environment:
      name: prod
    if: ${{ always() }}
    steps:
      - run: echo "hello always-after-prod"
      
  always-job:
    needs: always-after-prod
    runs-on: ubuntu-latest
    if: ${{ always() }}
    steps:
      - run: echo "yes"
    
  success-job:
    needs: always-after-prod
    runs-on: ubuntu-latest
    if: ${{ success() }}
    steps:
      - run: echo "yes"
      
  cancelled-job:
    needs: always-after-prod
    runs-on: ubuntu-latest
    if: ${{ cancelled() }}
    steps:
      - run: echo "yes"
      
  failure-job:
    needs: always-after-prod
    runs-on: ubuntu-latest
    if: ${{ failure() }}
    steps:
      - run: echo "yes"

  intermediate-job:
    needs: test-prod
    runs-on: ubuntu-latest
    if: ${{ always() && success() }}
    steps:
      - run: echo "hello intermediate"
      
  final-job:
    runs-on: ubuntu-latest
    needs:
     - test-prod
     - intermediate-job
    if: ${{ always() && success() && (github.event_name == 'push' || github.event_name == 'workflow_dispatch') }}
    environment:
      name: prod
    steps:
      - run: echo "hello final job"

  get_pr_labels:
    name: Get PR labels
    if: ${{ github.event_name == 'push' }}
    runs-on: ubuntu-latest
    outputs:
      labels: ${{ steps.get_pr_labels.outputs.labels }}
    steps:
      - uses: actions-ecosystem/action-get-merged-pull-request@v1.0.1
        id: get_pr_labels
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          
  some-job:
    runs-on: ubuntu-latest
    environment:
      name: ${{ matrix.env }}
    strategy:
      matrix:
        env: ["dev", "uat", "prod"]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: stuff
        run: ./test.sh ${{ secrets.mysecret }}
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
      - name: Dump job context
        env:
          JOB_CONTEXT: ${{ toJson(job) }}
        run: echo "$JOB_CONTEXT"
      - name: Dump steps context
        env:
          STEPS_CONTEXT: ${{ toJson(steps) }}
        run: echo "$STEPS_CONTEXT"
      - name: Dump runner context
        env:
          RUNNER_CONTEXT: ${{ toJson(runner) }}
        run: echo "$RUNNER_CONTEXT"
      - name: Dump strategy context
        env:
          STRATEGY_CONTEXT: ${{ toJson(strategy) }}
        run: echo "$STRATEGY_CONTEXT"
      - name: Dump matrix context
        env:
          MATRIX_CONTEXT: ${{ toJson(matrix) }}
        run: echo "$MATRIX_CONTEXT"
        
 # do_da_notes:
  #  name: Notes
   # runs-on: ubuntu-latest
    #needs: get_pr_labels
    
  print:
    name: Print
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: ./test.sh ${{ secrets.GITHUB_TOKEN }}
     
  publish_release_notes:
    environment:
      name: prod-approve
    permissions:
      contents: write
      pull-requests: read
    name: Publish release notes
    runs-on: ubuntu-latest
    needs: get_pr_labels    
    if: ${{ always() && github.event_name == 'workflow_dispatch' }}
    steps:
      - run: echo "publishing notes"
  
  build_api_job:
    name: Build/Test/Publish API Image
    runs-on: ubuntu-latest
    needs: 
      - publish_release_notes
      - get_pr_labels
    if: ${{ always() && !failure() }}
    steps:
      - run: echo "building api"
 
  deploy_dev_api_job:
    name: Deploy API to Development
    runs-on: ubuntu-latest
    needs: build_api_job
    environment:
      name: dev
    if: ${{ always() && !failure() && github.event_name != 'pull_request' }}
    steps:
      - run: echo "deploy to dev"
      
  deploy_prod_api_job:
    name: Deploy API to Production
    runs-on: ubuntu-latest
    environment:
      name: prod
    needs: 
      - build_api_job
      - publish_release_notes
      - get_pr_labels
    if: ${{ always() && !failure() && github.event_name == 'workflow_dispatch' }}
    steps:
      - run: echo "deploy to prod"